"""Shared helpers for LaunchPad content batch tooling.

Extracted from the per-batch generators so that quoting, the reflection
editorial rule, the common row validators and `.env.local` loading live in
exactly one place. See docs/plans/reusable-content-generator.md.

Deliberately stdlib-only and importable with no packaging: the scripts in
this directory are run as `python3 scripts/<name>.py` from the repo root,
which puts `scripts/` on `sys.path[0]`, so `import launchpad_content` just
works. Keep it that way.
"""

from __future__ import annotations

import os
import re
from collections import Counter
from pathlib import Path
from typing import Any


ENV_PATH = Path(".env.local")

# Reflection editorial rule. Canonical copy: this one. Previously triplicated
# across preflight-reflections.py, generate-reflections-migration.py and
# generate-print-nerd-migration.py with byte-identical constants.
WORD_MIN = 20
WORD_MAX = 50
SECOND_PERSON_RE = re.compile(r"\byou(?:r|rs|rself)?\b", re.IGNORECASE)
EM_DASH = "—"

SLUG_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
TITLE_MAX_CHARS = 100

KNOWN_CATEGORY_SLUGS = {
    "emerging-careers",
    "on-the-job",
    "life-skills",
    "mindsets",
    "how-i-got-here",
    "problems-to-solve",
    "post-secondary",
    "skilled-trades",
}


# --------------------------------------------------------------------------
# SQL quoting
# --------------------------------------------------------------------------

def sql(value: Any) -> str:
    """Render a Python value as a SQL literal.

    Subsumes the `quote()` helper the UPDATE generators used: that one lacked
    the None branch and the str() coercion, so every one of its call sites is
    covered by this with identical output.
    """
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def source_comment_path(source: Any) -> str:
    """Render a source path for a `-- Generated by ... from <path>.` comment.

    Always forward-slashed. `str(Path("scripts/data/x.json"))` yields
    backslashes on Windows, which would make every generated file differ from
    its committed counterpart and break the golden-file harness that the whole
    verification story rests on. On POSIX this is a no-op.
    """
    return str(source).replace(os.sep, "/").replace("\\", "/")


# --------------------------------------------------------------------------
# Environment
# --------------------------------------------------------------------------

def load_env() -> dict[str, str]:
    """Read `.env.local` relative to CWD, with process env taking precedence."""
    env = {**os.environ}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            env.setdefault(key.strip(), value.strip())
    return env


# --------------------------------------------------------------------------
# Editorial rule
# --------------------------------------------------------------------------

def row_ref(row: dict[str, Any]) -> Any:
    """Best available identifier for error messages."""
    return row.get("id") or row.get("content_id")


def validate_editorial_rule(
    index: int,
    row: dict[str, Any],
    field: str = "reflection",
) -> list[str]:
    """Enforce: 20-50 words, second-person, ends with '?', no em-dash, non-empty.

    All 279 authored reflections in the repo satisfy this, so it applies
    universally with no grandfathering.
    """
    errors: list[str] = []
    rid = row_ref(row)
    value = row.get(field)

    if not isinstance(value, str) or not value.strip():
        errors.append(f"row {index} ({rid}) empty {field}")
        return errors

    text = value.strip()
    word_count = len(text.split())

    if word_count < WORD_MIN or word_count > WORD_MAX:
        errors.append(
            f"row {index} ({rid}) {field} has {word_count} words; "
            f"expected {WORD_MIN}-{WORD_MAX}"
        )
    if not SECOND_PERSON_RE.search(text):
        errors.append(f"row {index} ({rid}) {field} must use second-person ('you'/'your')")
    if not text.endswith("?"):
        errors.append(f"row {index} ({rid}) {field} must end with '?'")
    if EM_DASH in text:
        errors.append(f"row {index} ({rid}) {field} contains em-dash; use a comma or colon")

    return errors


# --------------------------------------------------------------------------
# Common row / batch validators
# --------------------------------------------------------------------------

def validate_required_fields(
    index: int,
    row: dict[str, Any],
    fields: tuple[str, ...] | list[str],
) -> list[str]:
    """Strict presence check: an empty string is a failure, not a value.

    The seed generators used `not row.get(field)` and the UPDATE generators
    used `field not in row`. Unified on the strict form on purpose: an empty
    string should never be written into a column that is meant to hold copy.
    """
    missing = [field for field in fields if not row.get(field)]
    if missing:
        return [f"row {index} missing required fields: {', '.join(missing)}"]
    return []


def validate_title(index: int, title: Any) -> list[str]:
    if not isinstance(title, str):
        return [f"row {index} title must be a string, got {title!r}"]
    if len(title) > TITLE_MAX_CHARS:
        return [f"row {index} title exceeds content title limit: {len(title)} chars"]
    return []


def validate_slug(index: int, slug: Any) -> list[str]:
    if not isinstance(slug, str) or not SLUG_RE.fullmatch(slug):
        return [f"row {index} has invalid slug: {slug!r}"]
    return []


def validate_duration(index: int, duration: Any) -> list[str]:
    if not isinstance(duration, int) or isinstance(duration, bool) or duration <= 0:
        return [f"row {index} has invalid duration_seconds: {duration!r}"]
    return []


def validate_orientation(index: int, orientation: Any, expected: str | None = None) -> list[str]:
    if orientation not in ("vertical", "horizontal"):
        return [f"row {index} has invalid orientation: {orientation!r}"]
    if expected is not None and orientation != expected:
        return [f"row {index} has orientation {orientation!r}, expected {expected!r}"]
    return []


def validate_batch_identity(
    rows: list[dict[str, Any]],
    expected_count: int,
    id_prefix: str,
    unique_fields: tuple[str, ...] = ("content_id", "slug", "url"),
) -> list[str]:
    """Batch-level count, sequence, content_id and duplicate checks.

    Lifted from the three seed generators, which each carried an identical
    copy of this block.
    """
    errors: list[str] = []

    if len(rows) != expected_count:
        errors.append(f"row count is {len(rows)}, expected {expected_count}")

    expected_sequences = list(range(1, expected_count + 1))
    sequences = [row.get("sequence") for row in rows]
    if sequences != expected_sequences:
        errors.append(f"sequence values are {sequences}, expected {expected_sequences}")

    content_ids = [row.get("content_id") for row in rows]
    expected_ids = [f"{id_prefix}-{index:03d}" for index in expected_sequences]
    if content_ids != expected_ids:
        errors.append(f"content_id sequence is {content_ids}, expected {expected_ids}")

    for field_name in unique_fields:
        values = [row.get(field_name) for row in rows]
        duplicates = sorted(
            {value for value, count in Counter(values).items() if count > 1 and value is not None}
        )
        if duplicates:
            errors.append(f"duplicate {field_name} values: {duplicates}")

    return errors
